device: 'cuda'
checkpoint_load:
checkpoint_save:
log:
data_root: 'data/'

dataset: 'cifar100'
num_classes: 
input_height: 
input_width:
input_channel:

epochs: 100
batch_size: 256
num_workers: 4
lr: 0.01
lr_scheduler: CosineAnnealingLR

poison_rate: 0.1
target_type: 'all2one'
target_label: 0
trigger_type: 'squareTrigger'

model: 'preactresnet18'
random_seed: 0
index: 

acc_ratio: 0.1
ratio: 0.05

