# Note that since we add resize for different dataset, so the parameter name change in this framwork!
selected_layer_name: 1.heads.head
selected_layer_param_name: 1.heads.head.weight

num_neuron: 2
mask_path: ./resource/trojannn/apple4.png
neuron_target_values: 100
mask_update_iters: 1000
attack_label_trans: all2one
attack_target: 0
pratio: 0.1
attack: trojannn
model: vit_b_16