amp: False
device: cuda:0
attack_label_trans: all2one
attack_target: 0
client_optimizer: sgd
dataset: cifar10
dataset_path: ./data
frequency_save: 100
batch_size: 128
lr: 0.01
lr_scheduler: CosineAnnealingLR
model: preactresnet18
pratio: 0.1
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
attack: badnet
patch_mask_path: ../resource/badnet/bottom_right_3by3_white.npy
epochs: 100
result_file_defense: None
